on:
  pull_request:
    types: [opened, reopened, ready_for_review]
name: Auto Assign Pull Request
jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@v1