# https://github.com/marketplace/actions/issues-translator

name: 'issue-translator'
on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  translation:
    runs-on: ubuntu-latest
    steps:
      - uses: tomsun28/issues-translate-action@v2.7
        with:
          IS_MODIFY_TITLE: false
          CUSTOM_BOT_NOTE: Bot detected that issue body's language is not English, translated it automatically.